"""Shared Android report evidence contract text."""

from __future__ import annotations

import re
import shlex
from collections.abc import Iterable

from android_report_gate_contract import ANDROID_REPORT_GATE_MARKDOWN_FILE_NAME


ANDROID_REPORT_EVIDENCE_STATUS_PREFIX = "android_report_evidence_status"
ANDROID_REPORT_EVIDENCE_DRAFT_PREFIX = "android_report_evidence_draft"

ANDROID_REPORT_EVIDENCE_PASS_STATUS = "PASS"
ANDROID_REPORT_EVIDENCE_FAIL_STATUS = "FAIL"
ANDROID_REPORT_EVIDENCE_SAFE_REPORT_FILE_PATTERN = r"^[A-Za-z0-9._-]+\.json$"
ANDROID_REPORT_EVIDENCE_EXAMPLE_APP_USED = "example app"
ANDROID_REPORT_EVIDENCE_HOST_APP_USED = "host app"
ANDROID_REPORT_EVIDENCE_ALLOWED_APP_USED_VALUES = (
    ANDROID_REPORT_EVIDENCE_EXAMPLE_APP_USED,
    ANDROID_REPORT_EVIDENCE_HOST_APP_USED,
)
ANDROID_REPORT_EVIDENCE_APP_USED_PLACEHOLDER = " / ".join(
    ANDROID_REPORT_EVIDENCE_ALLOWED_APP_USED_VALUES
)

ANDROID_REPORT_EVIDENCE_RUN_CONTEXT_HEADING = "## Run Context"
ANDROID_REPORT_EVIDENCE_APP_SIDE_TRIGGER_HEADING = "## App-Side Trigger"
ANDROID_REPORT_EVIDENCE_HOST_OUTPUTS_HEADING = "## Host Outputs"
ANDROID_REPORT_EVIDENCE_HOST_COMMANDS_HEADING = "## Host Commands Run"
ANDROID_REPORT_EVIDENCE_HOST_COMMANDS_CODE_FENCE_START = "```bash"
ANDROID_REPORT_EVIDENCE_HOST_COMMANDS_CODE_FENCE_END = "```"
ANDROID_REPORT_EVIDENCE_ANALYZER_SCRIPT = "tool/analyze_diagnostics.py"
ANDROID_REPORT_EVIDENCE_DRAFT_BUILDER_SCRIPT = "tool/build_android_report_evidence.py"
ANDROID_REPORT_EVIDENCE_VALIDATOR_SCRIPT = "tool/validate_android_report_evidence.py"
ANDROID_REPORT_EVIDENCE_ANALYZER_GATE_OPTION = "--android-report-gate"
ANDROID_REPORT_EVIDENCE_ANALYSIS_OUTPUT_DIR_OPTION = "--analysis-output-dir"
ANDROID_REPORT_EVIDENCE_APPLICATION_ID_OPTION = "--application-id"
ANDROID_REPORT_EVIDENCE_BRANCH_OPTION = "--branch"
ANDROID_REPORT_EVIDENCE_COMMIT_OPTION = "--commit"
ANDROID_REPORT_EVIDENCE_OUTPUT_OPTION = "--output"
ANDROID_REPORT_EVIDENCE_GATE_MARKDOWN_OPTION = "--gate-markdown"
ANDROID_REPORT_EVIDENCE_DATE_OPTION = "--date"
ANDROID_REPORT_EVIDENCE_APP_USED_OPTION = "--app-used"
ANDROID_REPORT_EVIDENCE_APP_VARIANT_OPTION = "--app-variant"
ANDROID_REPORT_EVIDENCE_ANDROID_VERSION_OPTION = "--android-version"
ANDROID_REPORT_EVIDENCE_PYTHON_COMMAND = "python3"
ANDROID_REPORT_EVIDENCE_STDOUT_REDIRECT_TOKEN = ">"
ANDROID_REPORT_EVIDENCE_DEFAULT_APP_VARIANT = "debug"
ANDROID_REPORT_EVIDENCE_GIT_BRANCH_COMMAND = ("git", "branch", "--show-current")
ANDROID_REPORT_EVIDENCE_GIT_COMMIT_COMMAND = (
    "git",
    "rev-parse",
    "--short",
    "HEAD",
)
ANDROID_REPORT_EVIDENCE_DEVICE_REPORT_DIRECTORY = "files/performance_tier_reports"
ANDROID_REPORT_EVIDENCE_DATE_LABEL = "Date"
ANDROID_REPORT_EVIDENCE_BRANCH_LABEL = "Branch"
ANDROID_REPORT_EVIDENCE_COMMIT_LABEL = "Commit"
ANDROID_REPORT_EVIDENCE_APP_USED_LABEL = "App used"
ANDROID_REPORT_EVIDENCE_APP_VARIANT_LABEL = "App variant"
ANDROID_REPORT_EVIDENCE_APPLICATION_ID_LABEL = "Application id"
ANDROID_REPORT_EVIDENCE_DEVICE_MODEL_LABEL = "Device model"
ANDROID_REPORT_EVIDENCE_ANDROID_VERSION_LABEL = "Android version"
ANDROID_REPORT_EVIDENCE_SDK_INT_LABEL = "SDK int"
ANDROID_REPORT_EVIDENCE_RAM_LABEL = "RAM class / total RAM if known"
ANDROID_REPORT_EVIDENCE_THERMAL_POWER_LABEL = "Thermal / power state if relevant"
ANDROID_REPORT_EVIDENCE_TRIGGER_PATH_LABEL = "Trigger path"
ANDROID_REPORT_EVIDENCE_REPORT_LIST_REFRESHED_LABEL = "Report list refreshed with"
ANDROID_REPORT_EVIDENCE_COPY_SOURCE_LABEL = "Copy source"
ANDROID_REPORT_EVIDENCE_ON_DEVICE_DIRECTORY_LABEL = "On-device directory"
ANDROID_REPORT_EVIDENCE_REPORT_FILE_NAME_LABEL = "Report file name"
ANDROID_REPORT_EVIDENCE_COPIED_COMMANDS_AVAILABLE_LABEL = (
    "Copied commands were available for a safe `.json` report file name"
)
ANDROID_REPORT_EVIDENCE_HOST_COMMAND_ORDER_LABEL = "Host command order"
ANDROID_REPORT_EVIDENCE_PULLED_REPORT_PATH_LABEL = "Pulled report path"
ANDROID_REPORT_EVIDENCE_ANALYZER_OUTPUT_DIRECTORY_LABEL = (
    "Analyzer output directory"
)
ANDROID_REPORT_EVIDENCE_ANALYZER_EXIT_CODE_LABEL = "Analyzer exit code"
ANDROID_REPORT_EVIDENCE_GATE_STATUS_LABEL = (
    f"`{ANDROID_REPORT_GATE_MARKDOWN_FILE_NAME}` status"
)
ANDROID_REPORT_EVIDENCE_TRIGGER_PATH_VALUE = (
    "`Internal Tools` -> `Generate report`"
)
ANDROID_REPORT_EVIDENCE_REPORT_LIST_REFRESHED_VALUE = (
    "`Internal Tools` -> `List reports`"
)
ANDROID_REPORT_EVIDENCE_COPY_SOURCE_VALUE = (
    "`Internal Tools` -> `Copy host commands`"
)
ANDROID_REPORT_EVIDENCE_ON_DEVICE_DIRECTORY_VALUE = (
    f"`{ANDROID_REPORT_EVIDENCE_DEVICE_REPORT_DIRECTORY}/`"
)
ANDROID_REPORT_EVIDENCE_REQUIRED_APP_TRIGGER_VALUES = {
    ANDROID_REPORT_EVIDENCE_TRIGGER_PATH_LABEL: (
        ANDROID_REPORT_EVIDENCE_TRIGGER_PATH_VALUE
    ),
    ANDROID_REPORT_EVIDENCE_REPORT_LIST_REFRESHED_LABEL: (
        ANDROID_REPORT_EVIDENCE_REPORT_LIST_REFRESHED_VALUE
    ),
    ANDROID_REPORT_EVIDENCE_COPY_SOURCE_LABEL: (
        ANDROID_REPORT_EVIDENCE_COPY_SOURCE_VALUE
    ),
    ANDROID_REPORT_EVIDENCE_ON_DEVICE_DIRECTORY_LABEL: (
        ANDROID_REPORT_EVIDENCE_ON_DEVICE_DIRECTORY_VALUE
    ),
}
ANDROID_REPORT_EVIDENCE_RUN_CONTEXT_LABELS = [
    ANDROID_REPORT_EVIDENCE_DATE_LABEL,
    ANDROID_REPORT_EVIDENCE_BRANCH_LABEL,
    ANDROID_REPORT_EVIDENCE_COMMIT_LABEL,
    ANDROID_REPORT_EVIDENCE_APP_USED_LABEL,
    ANDROID_REPORT_EVIDENCE_APP_VARIANT_LABEL,
    ANDROID_REPORT_EVIDENCE_APPLICATION_ID_LABEL,
    ANDROID_REPORT_EVIDENCE_DEVICE_MODEL_LABEL,
    ANDROID_REPORT_EVIDENCE_ANDROID_VERSION_LABEL,
    ANDROID_REPORT_EVIDENCE_SDK_INT_LABEL,
]
ANDROID_REPORT_EVIDENCE_OPTIONAL_RUN_CONTEXT_LABELS = [
    ANDROID_REPORT_EVIDENCE_RAM_LABEL,
    ANDROID_REPORT_EVIDENCE_THERMAL_POWER_LABEL,
]
ANDROID_REPORT_EVIDENCE_APP_TRIGGER_LABELS = [
    *ANDROID_REPORT_EVIDENCE_REQUIRED_APP_TRIGGER_VALUES.keys(),
    ANDROID_REPORT_EVIDENCE_REPORT_FILE_NAME_LABEL,
    ANDROID_REPORT_EVIDENCE_COPIED_COMMANDS_AVAILABLE_LABEL,
]
ANDROID_REPORT_EVIDENCE_GENERATED_APP_TRIGGER_LABELS = [
    *ANDROID_REPORT_EVIDENCE_APP_TRIGGER_LABELS,
    ANDROID_REPORT_EVIDENCE_HOST_COMMAND_ORDER_LABEL,
]
ANDROID_REPORT_EVIDENCE_HOST_OUTPUT_CONTEXT_LABELS = [
    ANDROID_REPORT_EVIDENCE_PULLED_REPORT_PATH_LABEL,
    ANDROID_REPORT_EVIDENCE_ANALYZER_OUTPUT_DIRECTORY_LABEL,
]
ANDROID_REPORT_EVIDENCE_HOST_OUTPUT_LABELS = [
    *ANDROID_REPORT_EVIDENCE_HOST_OUTPUT_CONTEXT_LABELS,
    ANDROID_REPORT_EVIDENCE_ANALYZER_EXIT_CODE_LABEL,
    ANDROID_REPORT_EVIDENCE_GATE_STATUS_LABEL,
]
ANDROID_REPORT_EVIDENCE_CORE_CONTEXT_LABELS = [
    *ANDROID_REPORT_EVIDENCE_RUN_CONTEXT_LABELS,
    ANDROID_REPORT_EVIDENCE_REPORT_FILE_NAME_LABEL,
    *ANDROID_REPORT_EVIDENCE_HOST_OUTPUT_CONTEXT_LABELS,
]
ANDROID_REPORT_EVIDENCE_FIELD_SECTIONS = {
    **{
        label: ANDROID_REPORT_EVIDENCE_RUN_CONTEXT_HEADING
        for label in ANDROID_REPORT_EVIDENCE_RUN_CONTEXT_LABELS
    },
    **{
        label: ANDROID_REPORT_EVIDENCE_APP_SIDE_TRIGGER_HEADING
        for label in ANDROID_REPORT_EVIDENCE_APP_TRIGGER_LABELS
    },
    **{
        label: ANDROID_REPORT_EVIDENCE_HOST_OUTPUTS_HEADING
        for label in ANDROID_REPORT_EVIDENCE_HOST_OUTPUT_LABELS
    },
}
ANDROID_REPORT_EVIDENCE_FAIL_FAST_START_COMMAND = "set -e"
ANDROID_REPORT_EVIDENCE_ALLOW_GATE_FAIL_COMMAND = "set +e"
ANDROID_REPORT_EVIDENCE_GATE_STATUS_CAPTURE_COMMAND = "gate_status=$?"
ANDROID_REPORT_EVIDENCE_GATE_STATUS_CHECK_COMMAND = 'test "$gate_status" -eq 0'
ANDROID_REPORT_EVIDENCE_GATE_STATUS_CHECK_ARGV = [
    "test",
    "$gate_status",
    "-eq",
    "0",
]
ANDROID_REPORT_EVIDENCE_ADB_LIST_ARGV_PREFIX = [
    "adb",
    "shell",
    "run-as",
]
ANDROID_REPORT_EVIDENCE_ADB_PULL_ARGV_PREFIX = [
    "adb",
    "exec-out",
    "run-as",
]
ANDROID_REPORT_EVIDENCE_ADB_LIST_COMMAND = "ls"
ANDROID_REPORT_EVIDENCE_ADB_PULL_COMMAND = "cat"
ANDROID_REPORT_EVIDENCE_HOST_DIR_PREPARE_ARGV_PREFIX = ["mkdir", "-p"]
ANDROID_REPORT_EVIDENCE_NONEMPTY_REPORT_CHECK_ARGV_PREFIX = ["test", "-s"]
ANDROID_REPORT_EVIDENCE_GATE_MARKDOWN_PRINT_ARGV_PREFIX = ["cat"]

ANDROID_REPORT_EVIDENCE_STAGE_FAIL_FAST_START = "fail_fast_start"
ANDROID_REPORT_EVIDENCE_STAGE_LIST_REPORTS = "list_reports"
ANDROID_REPORT_EVIDENCE_STAGE_PREPARE_HOST_DIR = "prepare_host_dir"
ANDROID_REPORT_EVIDENCE_STAGE_PULL = "pull"
ANDROID_REPORT_EVIDENCE_STAGE_NONEMPTY_CHECK = "nonempty_check"
ANDROID_REPORT_EVIDENCE_STAGE_ALLOW_GATE_FAIL = "allow_gate_fail"
ANDROID_REPORT_EVIDENCE_STAGE_ANALYZER = "analyzer"
ANDROID_REPORT_EVIDENCE_STAGE_GATE_STATUS_CAPTURE = "gate_status_capture"
ANDROID_REPORT_EVIDENCE_STAGE_FAIL_FAST_RESUME = "fail_fast_resume"
ANDROID_REPORT_EVIDENCE_STAGE_GATE_MARKDOWN_PRINT = "gate_markdown_print"
ANDROID_REPORT_EVIDENCE_STAGE_GATE_STATUS_CHECK = "gate_status_check"
ANDROID_REPORT_EVIDENCE_STAGE_BUILDER = "builder"
ANDROID_REPORT_EVIDENCE_STAGE_VALIDATOR = "validator"

ANDROID_REPORT_EVIDENCE_REQUIRED_HOST_COMMAND_SNIPPETS = [
    ANDROID_REPORT_EVIDENCE_FAIL_FAST_START_COMMAND,
    ANDROID_REPORT_EVIDENCE_PYTHON_COMMAND,
    " ".join(ANDROID_REPORT_EVIDENCE_ADB_LIST_ARGV_PREFIX),
    " ".join(ANDROID_REPORT_EVIDENCE_HOST_DIR_PREPARE_ARGV_PREFIX),
    " ".join(ANDROID_REPORT_EVIDENCE_ADB_PULL_ARGV_PREFIX),
    ANDROID_REPORT_EVIDENCE_STDOUT_REDIRECT_TOKEN,
    " ".join(ANDROID_REPORT_EVIDENCE_NONEMPTY_REPORT_CHECK_ARGV_PREFIX),
    ANDROID_REPORT_EVIDENCE_ALLOW_GATE_FAIL_COMMAND,
    ANDROID_REPORT_EVIDENCE_ANALYZER_SCRIPT,
    ANDROID_REPORT_EVIDENCE_ANALYZER_GATE_OPTION,
    ANDROID_REPORT_EVIDENCE_GATE_STATUS_CAPTURE_COMMAND,
    ANDROID_REPORT_GATE_MARKDOWN_FILE_NAME,
    ANDROID_REPORT_EVIDENCE_GATE_STATUS_CHECK_COMMAND,
    ANDROID_REPORT_EVIDENCE_DRAFT_BUILDER_SCRIPT,
    ANDROID_REPORT_EVIDENCE_ANALYSIS_OUTPUT_DIR_OPTION,
    ANDROID_REPORT_EVIDENCE_APPLICATION_ID_OPTION,
    ANDROID_REPORT_EVIDENCE_BRANCH_OPTION,
    ANDROID_REPORT_EVIDENCE_COMMIT_OPTION,
    ANDROID_REPORT_EVIDENCE_OUTPUT_OPTION,
    ANDROID_REPORT_EVIDENCE_VALIDATOR_SCRIPT,
]

ANDROID_REPORT_EVIDENCE_HOST_COMMAND_STAGE_ORDER = [
    (ANDROID_REPORT_EVIDENCE_STAGE_FAIL_FAST_START, "start fail-fast"),
    (ANDROID_REPORT_EVIDENCE_STAGE_LIST_REPORTS, "list report directory"),
    (ANDROID_REPORT_EVIDENCE_STAGE_PREPARE_HOST_DIR, "prepare host report directory"),
    (ANDROID_REPORT_EVIDENCE_STAGE_PULL, "pull report"),
    (ANDROID_REPORT_EVIDENCE_STAGE_NONEMPTY_CHECK, "nonempty report check"),
    (ANDROID_REPORT_EVIDENCE_STAGE_ALLOW_GATE_FAIL, "allow analyzer gate failure capture"),
    (ANDROID_REPORT_EVIDENCE_STAGE_ANALYZER, "analyzer gate"),
    (ANDROID_REPORT_EVIDENCE_STAGE_GATE_STATUS_CAPTURE, "capture gate status"),
    (ANDROID_REPORT_EVIDENCE_STAGE_FAIL_FAST_RESUME, "resume fail-fast"),
    (ANDROID_REPORT_EVIDENCE_STAGE_GATE_MARKDOWN_PRINT, "gate markdown print"),
    (ANDROID_REPORT_EVIDENCE_STAGE_GATE_STATUS_CHECK, "gate status check"),
    (ANDROID_REPORT_EVIDENCE_STAGE_BUILDER, "evidence builder"),
    (ANDROID_REPORT_EVIDENCE_STAGE_VALIDATOR, "evidence validator"),
]

ANDROID_REPORT_EVIDENCE_HOST_COMMAND_ORDER_TEXT = " -> ".join(
    label for _stage, label in ANDROID_REPORT_EVIDENCE_HOST_COMMAND_STAGE_ORDER
)

ANDROID_REPORT_EVIDENCE_RESULT_HEADING = "## Result"
ANDROID_REPORT_EVIDENCE_PASS_FAIL_LABEL = "Pass / fail"
ANDROID_REPORT_EVIDENCE_FAILURE_CATEGORY_LABEL = "If failed, failure category"
ANDROID_REPORT_EVIDENCE_NOTES_LABEL = "Notes"

ANDROID_REPORT_EVIDENCE_PASS_RESULT = "Pass"
ANDROID_REPORT_EVIDENCE_FAIL_RESULT = "fail"
ANDROID_REPORT_EVIDENCE_NO_FAILURE_CATEGORY = "none"
ANDROID_REPORT_EVIDENCE_GATE_FAILURE_CATEGORY = "gate"

ANDROID_REPORT_EVIDENCE_FAILURE_CATEGORY_PLACEHOLDER = (
    "none / generation / storage / retrieval / parsing / gate"
)

ANDROID_REPORT_EVIDENCE_RESULT_LABELS = [
    ANDROID_REPORT_EVIDENCE_PASS_FAIL_LABEL,
    ANDROID_REPORT_EVIDENCE_FAILURE_CATEGORY_LABEL,
    ANDROID_REPORT_EVIDENCE_NOTES_LABEL,
]


def evidence_status_line(status: str) -> str:
    return f"{ANDROID_REPORT_EVIDENCE_STATUS_PREFIX}={status}"


def evidence_draft_line(value: str) -> str:
    return f"{ANDROID_REPORT_EVIDENCE_DRAFT_PREFIX}={value}"


def android_report_device_path(report_file_name: str) -> str:
    return f"{ANDROID_REPORT_EVIDENCE_DEVICE_REPORT_DIRECTORY}/{report_file_name}"


def host_command_argv_text(argv: Iterable[str]) -> str:
    return " ".join(shlex.quote(token) for token in argv)


def host_path_basename(value: str) -> str:
    return re.split(r"[\\/]", value.strip())[-1]


def is_safe_report_file_name(file_name: str) -> bool:
    return re.fullmatch(
        ANDROID_REPORT_EVIDENCE_SAFE_REPORT_FILE_PATTERN,
        file_name,
    ) is not None
